### ISSUE TITLE
documentation for custom corrections?

### ISSUE THREAD

**Issue by tvandervorm** [dmoonfire/atom-autocorrect#2]
I'd like to use this package to correct some common spelling mistakes that I make, however I'm not sure how I would go about adding my own word lists.

I've seen that a grammar file can be defined in the package settings, it would be very helpful if you could give a simple example in the readme of what the structure of such a grammar file should be. 

Thanks in advance

**Comment by dmoonfire** [comment]
Documentation? What's that? :) I'll add it to my list of things to do. Thank you.

**Comment by dmoonfire** [comment]
@tvandervorm: I have a PR pushed up to add documentation for how to implement a plugin. Would you be willing to look at the [instructions](https://github.com/dmoonfire/atom-autocorrect/blob/67eed22502a138f7a799fb1168bc060a9a5543b6/docs/plugins.md) and see if they make sense to you or if there is an area I could improve before committing?

**Comment by tvandervorm** [comment]
Thanks for taking the time to do this, I'll have a look and play around with it this weekend to see if I can get it to work, will let you know here how it goes.

**Comment by dmoonfire** [comment]
I'm going to mark that PR as done. If you have more questions, feel free to reopen this issue and we'll talk. Thank you!
